"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const elementUi_common = require("./node_modules/element-ui/lib/element-ui.common.js");
const zhCN = require("./node_modules/element-ui/lib/locale/lang/zh-CN.js");
require("./styles/index.js");
require("./cn-tags/index.js");
const index$1 = require("./cn-pagination/src/index.js");
require("./cn-badge/index.js");
require("./cn-form/index.js");
const elementUi_common$1 = require("./_virtual/element-ui.common.js");
const index = require("./cn-tags/src/index.js");
const index$2 = require("./cn-badge/src/index.js");
const index$3 = require("./cn-form/src/index.js");
const components = [
  index,
  index$1,
  index$2,
  index$3
];
const install = function(Vue, config = {}) {
  console.log(config, elementUi_common$1.elementUi_common.exports.MessageBox);
  Vue.use(elementUi_common, zhCN);
  components.forEach((component) => {
    Vue.component(component.name, component);
  });
};
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}
console.log(elementUi_common$1.elementUi_common.exports.MessageBox);
exports.CnTags = index;
exports.Alert = elementUi_common$1.elementUi_common.exports.Alert;
exports.Aside = elementUi_common$1.elementUi_common.exports.Aside;
exports.Autocomplete = elementUi_common$1.elementUi_common.exports.Autocomplete;
exports.Avatar = elementUi_common$1.elementUi_common.exports.Avatar;
exports.Backtop = elementUi_common$1.elementUi_common.exports.Backtop;
exports.Badge = elementUi_common$1.elementUi_common.exports.Badge;
exports.Breadcrumb = elementUi_common$1.elementUi_common.exports.Breadcrumb;
exports.BreadcrumbItem = elementUi_common$1.elementUi_common.exports.BreadcrumbItem;
exports.Button = elementUi_common$1.elementUi_common.exports.Button;
exports.ButtonGroup = elementUi_common$1.elementUi_common.exports.ButtonGroup;
exports.Calendar = elementUi_common$1.elementUi_common.exports.Calendar;
exports.Card = elementUi_common$1.elementUi_common.exports.Card;
exports.Carousel = elementUi_common$1.elementUi_common.exports.Carousel;
exports.CarouselItem = elementUi_common$1.elementUi_common.exports.CarouselItem;
exports.Cascader = elementUi_common$1.elementUi_common.exports.Cascader;
exports.CascaderPanel = elementUi_common$1.elementUi_common.exports.CascaderPanel;
exports.Checkbox = elementUi_common$1.elementUi_common.exports.Checkbox;
exports.CheckboxButton = elementUi_common$1.elementUi_common.exports.CheckboxButton;
exports.CheckboxGroup = elementUi_common$1.elementUi_common.exports.CheckboxGroup;
exports.Col = elementUi_common$1.elementUi_common.exports.Col;
exports.Collapse = elementUi_common$1.elementUi_common.exports.Collapse;
exports.CollapseItem = elementUi_common$1.elementUi_common.exports.CollapseItem;
exports.ColorPicker = elementUi_common$1.elementUi_common.exports.ColorPicker;
exports.Container = elementUi_common$1.elementUi_common.exports.Container;
exports.DatePicker = elementUi_common$1.elementUi_common.exports.DatePicker;
exports.Descriptions = elementUi_common$1.elementUi_common.exports.Descriptions;
exports.DescriptionsItem = elementUi_common$1.elementUi_common.exports.DescriptionsItem;
exports.Dialog = elementUi_common$1.elementUi_common.exports.Dialog;
exports.Divider = elementUi_common$1.elementUi_common.exports.Divider;
exports.Drawer = elementUi_common$1.elementUi_common.exports.Drawer;
exports.Dropdown = elementUi_common$1.elementUi_common.exports.Dropdown;
exports.DropdownItem = elementUi_common$1.elementUi_common.exports.DropdownItem;
exports.DropdownMenu = elementUi_common$1.elementUi_common.exports.DropdownMenu;
exports.Empty = elementUi_common$1.elementUi_common.exports.Empty;
exports.Footer = elementUi_common$1.elementUi_common.exports.Footer;
exports.Form = elementUi_common$1.elementUi_common.exports.Form;
exports.FormItem = elementUi_common$1.elementUi_common.exports.FormItem;
exports.Header = elementUi_common$1.elementUi_common.exports.Header;
exports.Icon = elementUi_common$1.elementUi_common.exports.Icon;
exports.Image = elementUi_common$1.elementUi_common.exports.Image;
exports.InfiniteScroll = elementUi_common$1.elementUi_common.exports.InfiniteScroll;
exports.Input = elementUi_common$1.elementUi_common.exports.Input;
exports.InputNumber = elementUi_common$1.elementUi_common.exports.InputNumber;
exports.Link = elementUi_common$1.elementUi_common.exports.Link;
exports.Loading = elementUi_common$1.elementUi_common.exports.Loading;
exports.Main = elementUi_common$1.elementUi_common.exports.Main;
exports.Menu = elementUi_common$1.elementUi_common.exports.Menu;
exports.MenuItem = elementUi_common$1.elementUi_common.exports.MenuItem;
exports.MenuItemGroup = elementUi_common$1.elementUi_common.exports.MenuItemGroup;
exports.Message = elementUi_common$1.elementUi_common.exports.Message;
exports.MessageBox = elementUi_common$1.elementUi_common.exports.MessageBox;
exports.Notification = elementUi_common$1.elementUi_common.exports.Notification;
exports.Option = elementUi_common$1.elementUi_common.exports.Option;
exports.OptionGroup = elementUi_common$1.elementUi_common.exports.OptionGroup;
exports.PageHeader = elementUi_common$1.elementUi_common.exports.PageHeader;
exports.Pagination = elementUi_common$1.elementUi_common.exports.Pagination;
exports.Popconfirm = elementUi_common$1.elementUi_common.exports.Popconfirm;
exports.Popover = elementUi_common$1.elementUi_common.exports.Popover;
exports.Progress = elementUi_common$1.elementUi_common.exports.Progress;
exports.Radio = elementUi_common$1.elementUi_common.exports.Radio;
exports.RadioButton = elementUi_common$1.elementUi_common.exports.RadioButton;
exports.RadioGroup = elementUi_common$1.elementUi_common.exports.RadioGroup;
exports.Rate = elementUi_common$1.elementUi_common.exports.Rate;
exports.Result = elementUi_common$1.elementUi_common.exports.Result;
exports.Row = elementUi_common$1.elementUi_common.exports.Row;
exports.Select = elementUi_common$1.elementUi_common.exports.Select;
exports.Skeleton = elementUi_common$1.elementUi_common.exports.Skeleton;
exports.SkeletonItem = elementUi_common$1.elementUi_common.exports.SkeletonItem;
exports.Slider = elementUi_common$1.elementUi_common.exports.Slider;
exports.Spinner = elementUi_common$1.elementUi_common.exports.Spinner;
exports.Step = elementUi_common$1.elementUi_common.exports.Step;
exports.Steps = elementUi_common$1.elementUi_common.exports.Steps;
exports.Submenu = elementUi_common$1.elementUi_common.exports.Submenu;
exports.Switch = elementUi_common$1.elementUi_common.exports.Switch;
exports.TabPane = elementUi_common$1.elementUi_common.exports.TabPane;
exports.Table = elementUi_common$1.elementUi_common.exports.Table;
exports.TableColumn = elementUi_common$1.elementUi_common.exports.TableColumn;
exports.Tabs = elementUi_common$1.elementUi_common.exports.Tabs;
exports.Tag = elementUi_common$1.elementUi_common.exports.Tag;
exports.TimePicker = elementUi_common$1.elementUi_common.exports.TimePicker;
exports.TimeSelect = elementUi_common$1.elementUi_common.exports.TimeSelect;
exports.Timeline = elementUi_common$1.elementUi_common.exports.Timeline;
exports.TimelineItem = elementUi_common$1.elementUi_common.exports.TimelineItem;
exports.Tooltip = elementUi_common$1.elementUi_common.exports.Tooltip;
exports.Transfer = elementUi_common$1.elementUi_common.exports.Transfer;
exports.Tree = elementUi_common$1.elementUi_common.exports.Tree;
exports.Upload = elementUi_common$1.elementUi_common.exports.Upload;
exports.default = install;
